// src/app/layout.tsx

import "@/styles/variables.scss";
import "@/styles/globals.scss";
import "@/styles/components/_btn.scss";
import "@/styles/components/_form.scss";
import "@/styles/components/_checkbox.scss";
import { AuthProvider } from "@/features/auth/context/AuthContext";
import CookieBanner from "@/components/CookieBanner/CookieBanner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="layout-container">
        <AuthProvider>
          {children}
          <CookieBanner />
        </AuthProvider>
      </body>
    </html>
  );
}
